# Generated by Django 2.1.5 on 2019-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191221_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
