# Generated by Django 2.1.5 on 2019-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191221_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_detail', models.CharField(max_length=100)),
                ('description_detail', models.TextField()),
                ('image_detail_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
