# Generated by Django 2.1.5 on 2019-12-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDetails',
        ),
    ]
