# Generated by Django 2.1.5 on 2019-12-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='first_name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='email',
            name='last_name',
        ),
    ]
